version: '3.8'

services:
  app:
    image: hello-front-dev
    build:
      context: . 
      dockerfile: dev.Dockerfile
    environment:      
      REACT_APP_BACKEND_URL: http://localhost:3000
    volumes:
      - ./:/usr/src/app
    ports:
      - 3217:3000
    container_name: hello-front-dev
  
  debug-helper:
    image: busybox
    
